apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arena-hendelse-proxy
  namespace: aap
  labels:
    team: aap
    sub: arena-hendelse-proxy
spec:
  image: {{image}}
  ingresses:
    - https://aap-arena-hendelse-proxy.intern.dev.nav.no
  replicas:
    min: 2
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: arena
  liveness:
    path: /actuator/live
  readiness:
    path: /actuator/ready
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
